// 색상이나 CSS 속성이 아니라 로그인·회원가입 화면에서 맡는 UI 역할을 이름으로 사용합니다.
export const authPageStyles = {
  page: 'grid min-h-screen place-items-center bg-[linear-gradient(135deg,#f8faff_0%,#eef2ff_100%)] px-4 py-8 text-app-ink',
  shell: 'grid w-full max-w-[960px] overflow-hidden rounded-[1.5rem] border border-[#e1e6f5] bg-white shadow-[0_24px_70px_rgb(47_67_129_/_14%)] md:grid-cols-[0.9fr_1.1fr]',
  introduction: 'flex flex-col justify-between bg-[linear-gradient(160deg,#1c2342_0%,#303875_100%)] p-7 text-[#e9edff] md:p-10',
  brand: 'flex items-center gap-3',
  brandMark: 'grid size-10 place-items-center rounded-[0.8rem] bg-brand-accent text-xl font-black text-[#17203d]',
  brandName: 'block text-lg font-extrabold tracking-[-0.04em]',
  brandSubtitle: 'mt-1 block text-xs text-[#a7b1d4]',
  introductionCopy: 'mt-16 md:mt-24',
  eyebrow: 'mb-3 text-xs font-extrabold tracking-[0.12em] text-[#b9e88f] uppercase',
  introductionTitle: 'm-0 max-w-[18rem] text-3xl font-extrabold leading-tight tracking-[-0.05em] md:text-4xl',
  introductionDescription: 'mt-5 max-w-[25rem] text-sm leading-7 text-[#c8d0eb]',
  trustNote: 'mt-12 border-t border-[rgb(219_227_255_/_15%)] pt-5 text-xs leading-6 text-[#a7b1d4]',
  formPanel: 'p-7 md:p-10',
  backLink: 'text-sm font-bold text-[#5e5fc8] no-underline',
  formHeader: 'mt-12',
  formTitle: 'm-0 text-2xl font-extrabold tracking-[-0.04em] text-[#182342]',
  formDescription: 'mt-3 text-sm leading-6 text-[#6d7898]',
  form: 'mt-8 grid gap-5',
  field: 'grid gap-2 text-sm font-bold text-[#3e4a6d]',
  checkboxField: 'flex items-start gap-2 text-xs leading-5 font-normal text-[#6d7898]',
  input: 'min-h-12 rounded-[0.7rem] border border-[#d7dcef] px-4 text-sm font-normal text-[#1b2544] outline-0 transition focus:border-[#7774d7] focus:shadow-[0_0_0_3px_rgb(119_116_215_/_15%)] aria-[invalid]:border-[#dcaab2]',
  fieldHint: 'text-xs font-normal leading-5 text-[#8a94ae]',
  fieldError: 'block text-xs font-normal leading-5 text-[#9a3947]',
  lookupRow: 'grid gap-2 sm:grid-cols-[1fr_auto]',
  lookupButton: 'min-h-12 cursor-pointer rounded-[0.7rem] border border-[#d7dcef] bg-[#f1f2ff] px-4 text-sm font-extrabold text-[#5e5fc8] disabled:cursor-not-allowed disabled:opacity-50',
  companyPanel: 'grid gap-2 rounded-[0.8rem] border border-[#d9edc8] bg-[#f5fbea] p-4 text-sm text-[#536d37]',
  companyRow: 'flex justify-between gap-4 border-b border-[rgb(83_109_55_/_12%)] py-1 last:border-0',
  companyValue: 'text-right font-extrabold',
  submitButton: 'min-h-12 cursor-pointer rounded-[0.7rem] border-0 bg-brand-primary px-5 text-sm font-extrabold text-white transition hover:bg-[#5051b8] disabled:cursor-not-allowed disabled:opacity-45',
  switchLink: 'text-center text-sm text-[#6d7898]',
  switchLinkAnchor: 'font-extrabold text-[#5e5fc8] no-underline',
  notice: 'rounded-[0.7rem] border border-[#d8ddec] bg-[#f7f8fc] px-3 py-2 text-xs leading-5 text-[#3e4a6d]',
  error: 'rounded-[0.7rem] border border-[#f0cfd4] bg-[#fff5f6] px-3 py-2 text-xs leading-5 text-[#9a3947]',
} as const
